name: Test

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NEXTEST_PROFILE: ci
  RUSTFLAGS: "-Awarnings"
  RUSTDOCFLAGS: "-Awarnings"

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.runner }}
    if: ${{ !startsWith(github.head_ref || github.ref_name, 'dependabot') }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable, nightly
          components: cargo, rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: test-${{ matrix.runner }}
          cache-all-crates: true
          cache-on-failure: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install cargo deps
        run: |
          cargo binstall -y --force cargo-nextest

      - name: Cargo Test
        id: cargo_test
        run: |
          cargo nextest run --all-features --profile ci


  coverage:
    name: Coverage
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: cargo, rustfmt, llvm-tools-preview
          toolchain: stable, nightly

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: coverage-${{ matrix.runner }}
          cache-all-crates: true
          cache-on-failure: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install cargo deps
        run: |
          cargo binstall -y --force cargo-llvm-cov
          cargo binstall -y --force cargo-nextest

      - name: Run coverage
        run: mise run coverage

      - name: Upload coverage reports
        if: ${{ matrix.runner == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ matrix.runner == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v5
        with:
          report_type: test_results
          token: ${{ secrets.CODECOV_TOKEN }}
